#ifndef QTBITINPUTPOLLER_GLOBAL_H
#define QTBITINPUTPOLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#if defined(QT_BUILD_BITINPUTPOLLER_LIB)
#  define QTBITINPUTPOLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTBITINPUTPOLLERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // QTBITINPUTPOLLER_GLOBAL_H
