#ifndef QTSERIALPORTASYNCBLOCK_GLOBAL_H
#define QTSERIALPORTASYNCBLOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#if defined(QT_SERIALPORTASYNCBLOCK_LIB)
#  define QTSERIALPORTASYNCBLOCK_EXPORT Q_DECL_EXPORT
#else
#  define QTSERIALPORTASYNCBLOCK_EXPORT Q_DECL_IMPORT
#endif
#endif

#endif // QTSERIALPORTASYNCBLOCK_GLOBAL_H
