name: build and unittest
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-metaproject
          name: buildroot
          workflow: buildAndExportArtifact.yml
          path: /github/home/install/
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Build
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          cd $HOME
          mkdir -p "$HOME/targetbuild"
          cd "$HOME/targetbuild"
          cmake $GITHUB_WORKSPACE \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc" \
           -DfirstBuild=ON
          # compile / install
           make -j $(getconf _NPROCESSORS_ONLN)
